project_id = "dhcvkahedldzqmtdcrjq"

[functions.ai-chat]
verify_jwt = false

[functions.text-to-voice]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.generate-blog]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.generate-itinerary-pdf]
verify_jwt = false