// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxymecevbjlvshobmqjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4eW1lY2V2YmpsdnNob2JtcWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzkxODksImV4cCI6MjA2MDY1NTE4OX0.xVKWe5KWyJ5K7-4rVbrvRKmVcsxtsz56Rf962SOJxPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);